package org.pmcsn.model;

public enum EventType {
    ARRIVAL_SMALL_CENTER,
    COMPLETION_SMALL_CENTER,
    ARRIVAL_MEDIUM_CENTER,
    COMPLETION_MEDIUM_CENTER,
    ARRIVAL_LARGE_CENTER,
    COMPLETION_LARGE_CENTER,
    ARRIVAL_RIDE_CENTER,
    COMPLETION_RIDE_CENTER,
    SAVE_STAT
}
